# Initialize

In [58]:
import pandas as pd
import numpy as np
import re

# Load data

In [73]:
TNS = pd.read_csv("tns_public_objects.csv",skiprows=1)

In [54]:
TNS.head()

,objid,name_prefix,name,ra,declination,redshift,typeid,type,reporting_groupid,reporting_group,...,source_group,discoverydate,discoverymag,discmagfilter,filter,reporters,time_received,internal_names,creationdate,lastmodified
0,95186,AT,2021acxj,56.209897,-6.178407,NaN,NaN,NaN,18.0,ATLAS,...,ATLAS,2021-10-31 11:03:50.400,19.598,71.0,cyan,"J. Tonry, L. Denneau, A. Heinze, H. Weiland (I...",2021-11-01 00:03:38,ATLAS21bldt,2021-11-01 00:03:38,2021-11-01 00:03:38
1,95185,AT,2021acxi,355.404620,-6.473544,NaN,NaN,NaN,18.0,ATLAS,...,ATLAS,2021-10-31 08:12:28.800,19.852,71.0,cyan,"J. Tonry, L. Denneau, A. Heinze, H. Weiland (I...",2021-11-01 00:03:03,ATLAS21blds,2021-11-01 00:03:04,2021-11-01 00:03:04
2,95184,AT,2021acxh,312.469017,3.341450,NaN,NaN,NaN,18.0,ATLAS,...,ATLAS,2021-10-31 06:25:55.200,19.237,71.0,cyan,"J. Tonry, L. Denneau, A. Heinze, H. Weiland (I...",2021-10-31 23:40:57,ATLAS21blcy,2021-10-31 23:40:59,2021-10-31 23:40:59
3,95183,AT,2021acxg,68.456500,-60.820611,NaN,NaN,NaN,36.0,MASTER,...,MASTER,2021-10-31 20:56:20.544,17.700,1.0,Clear,"Ya.Kechin, V. Lipunov, V.Kornilov, E.Gorbovsko...",2021-10-31 23:12:13,MASTER OT J043349.56-604914.2,2021-10-31 23:12:15,2021-10-31 23:12:15
4,95182,AT,2021acxf,24.122136,-7.602172,NaN,NaN,NaN,4.0,Pan-STARRS1,...,Pan-STARRS1,2021-10-30 08:05:16.800,20.730,26.0,w,"K. C. Chambers, T. de Boer, J. Bulger, J. Fair...",2021-10-31 22:00:15,PS21lst,2021-10-31 22:00:16,2021-10-31 22:00:16

# Convert to smaller table

In [78]:
TNSshort = TNS[['objid','name_prefix','name','internal_names','type','typeid']] # To make it easier to work with. Not used in the function.

# Extract ZTF

In [79]:
TNSshort['internal_names'] = TNSshort['internal_names'] + ',' # To make it searchable

/Users/davidivens/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [120]:
ZTFsub = 'ZTF' + TNSshort['internal_names'].str.extract('ZTF(.+?),')

In [121]:
ZTFextracts = pd.notna(ZTFsub)

In [122]:
TNSZTF = TNSshort[ZTFextracts.values]

In [123]:
TNSZTF['internal_names'] = ZTFsub

/Users/davidivens/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

# Count types

In [124]:
TNSZTF

       objid name_prefix      name internal_names     type  typeid
11     95175          AT  2021acwy   ZTF21acizlsw      NaN     NaN
12     95174          AT  2021acwx   ZTF21acjvqnq      NaN     NaN
13     95173          AT  2021acww   ZTF21acjjtmh      NaN     NaN
26     95160          AT  2021acwj   ZTF21acjxpdv      NaN     NaN
27     95159          AT  2021acwi   ZTF21acjxiyh      NaN     NaN
28     95158          AT  2021acwh   ZTF21acjxjpu      NaN     NaN
29     95157          AT  2021acwg   ZTF21acjvcre      NaN     NaN
30     95156          AT  2021acwf   ZTF21acjowmq      NaN     NaN
31     95155          AT  2021acwe   ZTF21abtzbub      NaN     NaN
32     95154          AT  2021acwd   ZTF21acizsqx      NaN     NaN
33     95153          AT  2021acwc   ZTF21acjvjhq      NaN     NaN
34     95152          AT  2021acwb   ZTF21acjpwbh      NaN     NaN
35     95151          AT  2021acwa   ZTF21acjouph      NaN     NaN
36     95150          AT  2021acvz   ZTF21ackastv      NaN     NaN
37     95149          AT  2021acvy   ZTF21ackarpj      NaN     NaN
38     95148          AT  2021acvx   ZTF21ackavjd      NaN     NaN
39     95147          AT  2021acvw   ZTF21acjqhoi      NaN     NaN
40     95146          AT  2021acvv   ZTF18aaewdgq      NaN     NaN
41     95145          AT  2021acvu   ZTF21acjgdxq      NaN     NaN
42     95144          AT  2021acvt   ZTF21acjpsqe      NaN     NaN
43     95143          AT  2021acvs   ZTF21acjrrex      NaN     NaN
44     95142          AT  2021acvr   ZTF21acjrrle      NaN     NaN
45     95141          AT  2021acvq   ZTF21acjvkga      NaN     NaN
50     95136          AT  2021acvl   ZTF21acjoorl      NaN     NaN
51     95135          AT  2021acvk   ZTF21acjxsrf      NaN     NaN
52     95134          AT  2021acvj   ZTF21acjjwmj      NaN     NaN
59     95127          AT  2021acvc   ZTF21acjxiqw      NaN     NaN
89     95097          AT  2021actz   ZTF21acioibf      NaN     NaN
90     95096          AT  2021acty   ZTF21acjqbgh      NaN     NaN
91     95095          AT  2021actx   ZTF21acjqdoa      NaN     NaN
...      ...         ...       ...            ...      ...     ...
81424  13475          AT   2016ecc   ZTF21abbxteb      NaN     NaN
81425  13474          AT   2016ecb   ZTF18ablvioz      NaN     NaN
81530  13368          AT   2016dxz   ZTF19aadbvxs      NaN     NaN
81536  13362          AT   2016dxt   ZTF17aaahrni      NaN     NaN
81582  13315          AT   2016dvy   ZTF20aawzrlj      NaN     NaN
81585  13312          AT   2016dvv   ZTF18aaiwsqa      NaN     NaN
81591  13306          AT   2016dvp   ZTF20abjnqcj      NaN     NaN
81617  13280          AT   2016dup   ZTF18abxmbfq      NaN     NaN
81644  13253          AT   2016dto   ZTF18ablwqqf  Varstar    28.0
81680  13217          AT   2016dse   ZTF18abdingc      NaN     NaN
81919  12976          AT   2016dix   ZTF18abmiqsz      NaN     NaN
82057  12838          AT   2016ddp   ZTF19abhfpok      NaN     NaN
82079  12816          AT   2016dct   ZTF18abgoaqz      NaN     NaN
82147  12748          AT   2016dad   ZTF19abbxpss      NaN     NaN
82201  12693          AT   2016cya   ZTF18abckxfb       CV    27.0
82242  12652          AT   2016cwl   ZTF18abxxhta      NaN     NaN
82382  12512          AT   2016crb   ZTF18aboirkq      NaN     NaN
82404  12489          AT   2016cqe   ZTF18abitnjn      NaN     NaN
82470  12421          AT   2016cnq   ZTF18aazvajy      NaN     NaN
83165  11721          AT   2016bmu   ZTF19aapbsrv      NaN     NaN
83190  11695          AT   2016blu   ZTF17aaapufz      LBV    24.0
83464  11420          AT   2016bbf   ZTF18acrxoqx      NaN     NaN
83537  11346          AT   2016ayj   ZTF19abudvoz      NaN     NaN
83555  11327          AT   2016axq   ZTF19aangfld      NaN     NaN
83839  11043          AT   2016amu   ZTF18acecpja      NaN     NaN
83916  10965          AT   2016ajv   ZTF19aabyoce      NaN     NaN
84251  10627          AT    2016wy   ZTF19aaioufy      NaN     NaN
84269  10609          AT    2016wg   ZTF19aaablrx      NaN     NaN
84295  10583          AT    2016vg   ZTF19acjiett      NaN     NaN
84669  10209          AT    2016gw   ZTF18abxvolr      NaN     NaN

[30552 rows x 6 columns]

# As a function

In [126]:
def ZTFandtype(csvfile):
    TNS = pd.read_csv(csvfile,skiprows=1)
    TNS['internal_names'] = TNS['internal_names'] + ','
    ZTFsub = 'ZTF' + TNS['internal_names'].str.extract('ZTF(.+?),')
    ZTFextracts = pd.notna(ZTFsub)
    TNSZTF = TNS[ZTFextracts.values]
    TNSZTF['internal_names'] = ZTFsub
    return TNSZTF